server:
  port: 8082


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/books
#    username: root
#    password: Welcome@23
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#logging:
#  level:
#    com.books.book.store: DEBUG


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: root
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect